"""empty message

Revision ID: 11d2a86166f
Revises: 2f224d25e688
Create Date: 2015-02-12 20:13:32.187775

"""

# revision identifiers, used by Alembic.
revision = '11d2a86166f'
down_revision = '2f224d25e688'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monkeyname', sa.String(length=64), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('avatar', sa.Integer(), nullable=True),
    sa.Column('best_friend', sa.String(length=64), nullable=True),
    sa.Column('pwdhash', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_age'), 'user', ['age'], unique=False)
    op.create_index(op.f('ix_user_best_friend'), 'user', ['best_friend'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_monkeyname'), 'user', ['monkeyname'], unique=True)
    op.create_table('banana_givers',
    sa.Column('giver_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['giver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banana_givers')
    op.drop_index(op.f('ix_user_monkeyname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_best_friend'), table_name='user')
    op.drop_index(op.f('ix_user_age'), table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
