"""empty message

Revision ID: 12cc28eb1ca9
Revises: ced7454a8c0
Create Date: 2015-02-08 18:59:23.789523

"""

# revision identifiers, used by Alembic.
revision = '12cc28eb1ca9'
down_revision = 'ced7454a8c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
