"""empty message

Revision ID: 132c13afed9f
Revises: 1cf2aefb4668
Create Date: 2015-02-08 17:43:44.705369

"""

# revision identifiers, used by Alembic.
revision = '132c13afed9f'
down_revision = '1cf2aefb4668'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receivers',
    sa.Column('giver_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['giver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], )
    )
    op.drop_table('reveivers')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reveivers',
    sa.Column('giver_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['giver_id'], [u'user.id'], name=u'reveivers_giver_id_fkey'),
    sa.ForeignKeyConstraint(['receiver_id'], [u'user.id'], name=u'reveivers_receiver_id_fkey')
    )
    op.drop_table('receivers')
    ### end Alembic commands ###
