"""empty message

Revision ID: 2f224d25e688
Revises: 53979a0e82f5
Create Date: 2015-02-10 11:43:17.431474

"""

# revision identifiers, used by Alembic.
revision = '2f224d25e688'
down_revision = '53979a0e82f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('best_friend', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_best_friend'), 'user', ['best_friend'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_best_friend'), table_name='user')
    op.drop_column('user', 'best_friend')
    ### end Alembic commands ###
