"""empty message

Revision ID: 418e3008ef2d
Revises: 12cc28eb1ca9
Create Date: 2015-02-08 19:41:32.061456

"""

# revision identifiers, used by Alembic.
revision = '418e3008ef2d'
down_revision = '12cc28eb1ca9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_monkeyname', table_name='user')
    op.create_index(op.f('ix_user_monkeyname'), 'user', ['monkeyname'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_monkeyname'), table_name='user')
    op.create_index('ix_user_monkeyname', 'user', ['monkeyname'], unique=False)
    ### end Alembic commands ###
