"""empty message

Revision ID: 437515c4908d
Revises: 45187e97117f
Create Date: 2015-02-04 15:22:43.052329

"""

# revision identifiers, used by Alembic.
revision = '437515c4908d'
down_revision = '45187e97117f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_monkeyname', table_name='users')
    op.create_index(op.f('ix_users_monkeyname'), 'users', ['monkeyname'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_monkeyname'), table_name='users')
    op.create_index('ix_users_monkeyname', 'users', ['monkeyname'], unique=True)
    ### end Alembic commands ###
