"""empty message

Revision ID: 4c670f50fd04
Revises: 59c88de6e4ff
Create Date: 2015-02-04 23:42:49.510687

"""

# revision identifiers, used by Alembic.
revision = '4c670f50fd04'
down_revision = '59c88de6e4ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('friend_a_id', sa.Integer(), nullable=True))
    op.add_column('followers', sa.Column('friend_b_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'followers_followed_id_fkey', 'followers', type_='foreignkey')
    op.drop_constraint(u'followers_follower_id_fkey', 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'user', ['friend_a_id'], ['id'])
    op.create_foreign_key(None, 'followers', 'user', ['friend_b_id'], ['id'])
    op.drop_column('followers', 'follower_id')
    op.drop_column('followers', 'followed_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('followers', sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key(u'followers_follower_id_fkey', 'followers', 'user', ['follower_id'], ['id'])
    op.create_foreign_key(u'followers_followed_id_fkey', 'followers', 'user', ['followed_id'], ['id'])
    op.drop_column('followers', 'friend_b_id')
    op.drop_column('followers', 'friend_a_id')
    ### end Alembic commands ###
