"""empty message

Revision ID: 4e76d74d882f
Revises: 437515c4908d
Create Date: 2015-02-04 18:18:49.475992

"""

# revision identifiers, used by Alembic.
revision = '4e76d74d882f'
down_revision = '437515c4908d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    ### end Alembic commands ###
