"""empty message

Revision ID: 53979a0e82f5
Revises: 55ee4d781f9b
Create Date: 2015-02-08 20:24:38.841263

"""

# revision identifiers, used by Alembic.
revision = '53979a0e82f5'
down_revision = '55ee4d781f9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
