"""empty message

Revision ID: 55ee4d781f9b
Revises: 418e3008ef2d
Create Date: 2015-02-08 19:43:40.334417

"""

# revision identifiers, used by Alembic.
revision = '55ee4d781f9b'
down_revision = '418e3008ef2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
